//categories
const GET_ALL_CATEGORIES='GET_ALL_CATEGORIES'

// posts
export const LOAD_POSTS = 'LOAD_POSTS'
export const LOAD_POST = 'LOAD_POST'
export const ADD_POST = 'ADD_POST'
export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'
export const UP_VOTE_POST = 'UP_VOTE_POST'
export const DOWN_VOTE_POST = 'DOWN_VOTE_POST'
export const GET_POSTS_FOR_CATEGORY = 'GET_POSTS_FOR_CATEGORY'
// export const FETCHING_POST='FETCHING_POST'
// export const FETCHING_POST_ERROR='FETCHING_POST_ERROR'
// export const FETCHING_POST_SUCCESS='FETCHING_POST_SUCCESS'
// export const REMOVE_FETCHING='REMOVE_FETCHING'
// export const ADD_POST='ADD_POST'
// export const ADD_MULTIPLE_POSTS='ADD_MULTIPLE_POSTS'


//sortedPosts
export const SORTED_POSTS = 'SORTED_POSTS'
export const SORTED_COMMENTS = 'SORTED_COMMENTS'

//COMMENTS
export const LOAD_COMMENTS_FOR_POST = 'LOAD_COMMENTS_FOR_POST'
export const ADD_COMMENT = 'ADD_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT'
export const DOWN_VOTE_COMMENT = 'DOWN_VOTE_COMMENT'

// export const ADD_COMMENT='ADD_COMMENT'
// export const ADD_COMMENT_ERROR='ADD_COMMENT_ERROR'
// export const REMOVE_COMMENT='REMOVE_COMMENT'
// export const FETCHING_COMMENTS='FETCHING_COMMENTS'
// export const FETCHING_COMMENTS_ERROR='FETCHING_COMMENTS_ERROR'
// export const FETCHING_COMMENTS_SUCCESS='FETCHING_COMMENTS_SUCCESS'



//Modal
export const OPEN_MODAL='OPEN_MODAL'
export const CLOSE_MODAL='CLOSE_MODAL'
export const UPDATE_POST_BODY='UPDATE_POST_BODY'


 //Feed

export const SETTING_FEED_LISTENER='SETTING_FEED_LISTENER'
export const SETTING_FEED_LISTENER_ERROR='SETTING_FEED_LISTENER_ERROR'
export const SETTING_FEED_LISTENER_SUCCESS='SETTING_FEED_LISTENER_SUCCESS'
 export const ADD_NEW_POST_ID_TO_FEED='ADD_NEW_POST_ID_TO_FEED'
 export const RESET_NEW_POSTS_AVAILABLE='RESET_NEW_POSTS_AVAILABLE'


//listenr
const ADD_LISTENER = 'ADD_LISTENER'




// // likeCount

// export const FETCHING_COUNT
// export const FETCHING_COUNT_ERROR
// export const FETCHING_COUNT_SUCCESS

