// posts
export const FETCHING_POST='FETCHING_POST'
export const FETCHING_POST_ERROR='FETCHING_POST_ERROR'
export const FETCHING_POST_SUCCESS='FETCHING_POST_SUCCESS'
export const REMOVE_FETCHING='REMOVE_FETCHING'
export const ADD_POST='ADD_POST'
export const ADD_MULTIPLE_POSTS='ADD_MULTIPLE_POSTS'


//COMMENTS
export const ADD_COMMENT='ADD_COMMENT'
export const ADD_COMMENT_ERROR='ADD_COMMENT_ERROR'
export const REMOVE_COMMENT='REMOVE_COMMENT'
export const FETCHING_COMMENTS='FETCHING_COMMENTS'
export const FETCHING_COMMENTS_ERROR='FETCHING_COMMENTS_ERROR'
export const FETCHING_COMMENTS_SUCCESS='FETCHING_COMMENTS_SUCCESS'



//Modal
export const OPEN_MODAL='OPEN_MODAL'
export const CLOSE_MODAL='CLOSE_MODAL'
export const UPDATE_POST_BODY='UPDATE_POST_BODY'


 //Feed

export const SETTING_FEED_LISTENER='SETTING_FEED_LISTENER'
export const SETTING_FEED_LISTENER_ERROR='SETTING_FEED_LISTENER_ERROR'
export const SETTING_FEED_LISTENER_SUCCESS='SETTING_FEED_LISTENER_SUCCESS'
 export const ADD_NEW_POST_ID_TO_FEED='ADD_NEW_POST_ID_TO_FEED'
 export const RESET_NEW_POSTS_AVAILABLE='RESET_NEW_POSTS_AVAILABLE'


// // likeCount

// export const FETCHING_COUNT
// export const FETCHING_COUNT_ERROR
// export const FETCHING_COUNT_SUCCESS

